//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Opptys
    {
        public int Id { get; set; }
        public string Customer { get; set; }
        public string Principal { get; set; }
        public string Engineer { get; set; }
        [DisplayName("Phone Number")]
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Program { get; set; }
        public string Application { get; set; }
        [DisplayName("Part Number")]
        public string Part_Number { get; set; }
        public string EAU { get; set; }
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Units Per Board")]
        public Nullable<int> Units_Per_Board { get; set; }
        [DisplayName("Decision Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yy}")]
        public Nullable<System.DateTime> Decision_Date { get; set; }
        [DisplayName("Production Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yy}")]
        public Nullable<System.DateTime> Production_Date { get; set; }
        public string CM { get; set; }
        [DisplayName("CM Location")]
        public string CM_Location { get; set; }
        public string Distributor { get; set; }
        [DisplayName("Disty Email")]
        public string Disty_Email { get; set; }
        [DisplayName("Disty Phone Number")]
        public string Disty_Phone_Number { get; set; }
        [DisplayName("Factory Email")]
        public string Factory_Email { get; set; }
        [DisplayName("Factory Phone Number")]
        public string Factory_Phone_Number { get; set; }
        public string Status { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yy}")]
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
