//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Strategy
    {
        [Key]
        public int StrategyId { get; set; }
        public string Customer { get; set; }
        public string EndProduct { get; set; }
        public string Product { get; set; }
        public string Status { get; set; }
        public string NextAction { get; set; }
        public string History { get; set; }
        [DisplayName("Created")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yy}")]
        public System.DateTime CreateDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yy}")]
        public Nullable<System.DateTime> Updated { get; set; }
        [DisplayName("F/U")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yy}")]
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        [DisplayName("Latest Comments")]
        public string ManagerComment { get; set; }
        public string OSR { get; set; }
        public string Principal { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Group { get; set; }
        public string Text { get; internal set; }
        public string Perm { get; set; }
        public WebApplication2.Models.EmailList p { get; set; }



        public List<SelectListItem> OSRcmb { get; set; }
        public IEnumerable<Strategy> Strategyddl { get; set; }
        //public List<SelectListItem> 
    }


}
